"""add answers column to match

Revision ID: 87fe7daeef75
Revises: 14defadfcbca
Create Date: 2025-07-29 09:20:53.318939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87fe7daeef75'
down_revision: Union[str, None] = '14defadfcbca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('answers', postgresql.ARRAY(sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match', 'answers')
    # ### end Alembic commands ###
