"""ajust img

Revision ID: fac1ce073a72
Revises: ffb22fec8608
Create Date: 2025-07-29 05:19:57.085733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac1ce073a72'
down_revision: Union[str, None] = 'ffb22fec8608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
